# AICOE AI Paper Pipeline Configuration

# arXiv fetcher settings
arxiv:
  # Categories to fetch papers from
  categories:
    - cs.AI    # Artificial Intelligence
    - cs.LG    # Machine Learning
    - cs.CV    # Computer Vision
    - cs.CL    # Computation and Language
    - cs.NE    # Neural and Evolutionary Computing
    - stat.ML  # Machine Learning (Statistics)
    - cs.RO    # Robotics
    - cs.HC    # Human-Computer Interaction
    - cs.IR    # Information Retrieval
  
  # Keywords for relevance scoring
  keywords:
    - llm
    - large language model
    - transformer
    - gpt
    - bert
    - claude
    - neural network
    - deep learning
    - reinforcement learning
    - computer vision
    - nlp
    - natural language
    - generative
    - diffusion
    - attention
    - multimodal
    - foundation model
    - fine-tuning
    - prompt
    - chain-of-thought
    - in-context learning
    - vision transformer
    - clip
    - stable diffusion
    - gan
    - federated learning
    - transfer learning
    - few-shot
    - zero-shot
    - rag
    - retrieval augmented
    - vector database
    - embedding
  
  # Maximum papers to fetch per category per run
  max_papers_per_category: 100
  
  # Minimum relevance score to process (0-10)
  min_relevance_score: 1.0
  
  # Rate limiting (seconds between API calls)
  rate_limit_seconds: 3

# Claude AI processor settings
claude:
  # API key (set as environment variable CLAUDE_API_KEY)
  api_key: ${CLAUDE_API_KEY}
  
  # Model to use
  model: claude-3-opus-20240229
  
  # Maximum tokens for response
  max_tokens: 4000
  
  # Temperature for generation
  temperature: 0.3
  
  # Batch size for processing
  batch_size: 5
  
  # Rate limit delay between requests (seconds)
  rate_limit_delay: 2

# HTML generator settings
generator:
  # Site title and description
  site_title: "AICOE Research Library"
  site_description: "Daily AI Papers - Summaries and Analysis"
  
  # Base URL for the site (update with your GitHub Pages URL)
  base_url: "https://yourusername.github.io/home/"
  
  # Number of papers to show on index page
  papers_per_page: 20
  
  # Generate RSS feed
  generate_rss: true

# GitHub settings
github:
  # Branch for GitHub Pages
  pages_branch: gh-pages
  
  # Commit message template
  commit_message: "📚 Update AI papers for {date}"
  
  # Auto-push to remote
  auto_push: true

# Schedule settings
schedule:
  # Times to run (24-hour format)
  times:
    - "09:00"  # 9 AM
    - "18:00"  # 6 PM
  
  # Timezone
  timezone: "UTC"
  
  # Days to run (0=Monday, 6=Sunday)
  days: [0, 1, 2, 3, 4, 5, 6]  # Every day

# Data directories
directories:
  data: "data"
  raw: "data/raw"
  processed: "data/processed"
  archive: "data/archive"
  templates: "templates"
  output: "docs"

# Processing options
processing:
  # Keep papers for N days before archiving
  retention_days: 30
  
  # Maximum papers to process per run
  max_papers_per_run: 50
  
  # Skip papers already processed
  skip_processed: true
  
  # Generate individual paper pages
  generate_paper_pages: true
  
  # Generate statistics
  generate_stats: true

# Notification settings (optional)
notifications:
  enabled: false
  
  # Email settings
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    from_address: ""
    to_addresses: []
  
  # Webhook for Slack/Discord
  webhook:
    enabled: false
    url: ""

# Logging
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: "pipeline.log"
  max_size_mb: 10
  backup_count: 5

# Feature flags
features:
  # Enable deduplication
  deduplication: true
  
  # Enable relevance scoring
  relevance_scoring: true
  
  # Enable Claude AI processing
  ai_processing: true
  
  # Enable automatic archiving
  auto_archive: true
  
  # Enable search functionality
  search: false
  
  # Enable paper recommendations
  recommendations: false