#!/bin/bash

# Test Commands for Research File Creation System
# Copy and paste any of these commands to test the system

echo "========================================="
echo "Research File Creation - Test Commands"
echo "========================================="
echo ""
echo "1. Create a new research file with today's date:"
echo ""
echo "cd /Users/srinivaskarri/Desktop/aicoe-home/home/Private/02-templates && python3 create_research_file.py \"Test Paper About AI Safety\""
echo ""
echo "----------------------------------------"
echo ""
echo "2. Create the 'Cognitively Faithful AI' paper properly:"
echo ""
echo "cd /Users/srinivaskarri/Desktop/aicoe-home/home/Private/02-templates && python3 create_research_file.py \"Cognitively Faithful AI Decision Making\""
echo ""
echo "----------------------------------------"
echo ""
echo "3. Create a research file with a custom date:"
echo ""
echo "cd /Users/srinivaskarri/Desktop/aicoe-home/home/Private/02-templates && python3 create_research_file.py \"LLM Evaluation Metrics Study\" \"2025-09-01\""
echo ""
echo "----------------------------------------"
echo ""
echo "4. View help and usage instructions:"
echo ""
echo "cd /Users/srinivaskarri/Desktop/aicoe-home/home/Private/02-templates && python3 create_research_file.py"
echo ""
echo "----------------------------------------"
echo ""
echo "5. List all research files to see naming convention:"
echo ""
echo "ls -la /Users/srinivaskarri/Desktop/aicoe-home/home/Private/03-research/"
echo ""
echo "========================================="